version: '3'

services:
  api:
    restart: always
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - hng
networks:
  hng:
